<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <meta http-equiv="Content-Style-Type" content="text/css">
  <title></title>
  <meta name="Generator" content="Cocoa HTML Writer">
  <meta name="CocoaVersion" content="1561.61">
  <style type="text/css">
    p.p1 {margin: 0.0px 0.0px 0.0px 0.0px; font: 14.0px Monaco; color: #f2f2f2; -webkit-text-stroke: #f2f2f2; background-color: #303030}
    span.s1 {font-kerning: none; text-shadow: 0.0px 1.0px 0.0px rgba(254, 254, 254, 0.0039)}
  </style>
</head>
<body>
<p class="p1"><span class="s1">plugins:</span></p>
<p class="p1"><span class="s1"><span class="Apple-converted-space">  </span>- jekyll-relative-links</span></p>
<p class="p1"><span class="s1">relative_links:</span></p>
<p class="p1"><span class="s1"><span class="Apple-converted-space">  </span>enabled: true</span></p>
<p class="p1"><span class="s1"><span class="Apple-converted-space">  </span>collections: true</span></p>
<p class="p1"><span class="s1">include:</span></p>
<p class="p1"><span class="s1"><span class="Apple-converted-space">  </span>- CONTRIBUTING.md</span></p>
<p class="p1"><span class="s1"><span class="Apple-converted-space">  </span>- README.md</span></p>
<p class="p1"><span class="s1"><span class="Apple-converted-space">  </span>- LICENSE.md</span></p>
<p class="p1"><span class="s1"><span class="Apple-converted-space">  </span>- COPYING.md</span></p>
<p class="p1"><span class="s1"><span class="Apple-converted-space">  </span>- CODE_OF_CONDUCT.md</span></p>
<p class="p1"><span class="s1"><span class="Apple-converted-space">  </span>- CONTRIBUTING.md</span></p>
<p class="p1"><span class="s1"><span class="Apple-converted-space">  </span>- ISSUE_TEMPLATE.md</span></p>
<p class="p1"><span class="s1"><span class="Apple-converted-space">  </span>- PULL_REQUEST_TEMPLATE.md</span></p>
</body>
</html>

theme: jekyll-theme-minimal